"""Add Field descriptions to all Pydantic models.

For each model, add a short Chinese description for each field based on the
endpoint path + field name.
"""
import re
from pathlib import Path

p = Path(r"D:\MoA Gateway Pro\moa_gateway\req_models.py")
src = p.read_text(encoding="utf-8")

# Description lookup
DESC = {
    'query': '查询文本 / 用户问题',
    'message': '消息内容',
    'messages': '消息列表',
    'role': '角色 (user/assistant/system)',
    'content': '内容',
    'name': '名称',
    'description': '描述',
    'preset': '预设名称 (如 balanced/quality/fast)',
    'presets': '预设列表',
    'proposers': '提议者列表,每个含 model_id 和 system_prompt',
    'aggregator': '聚合者 (model_id + synthesis_prompt)',
    'aggregators': '聚合者列表 (3-layer 模式需 3 个)',
    'model_id': '模型 ID (如 gpt-4o, deepseek-v3)',
    'model_ids': '模型 ID 列表',
    'candidate': '候选答案',
    'candidates': '候选答案列表',
    'options': '选项列表',
    'votes': '投票列表',
    'members': '成员列表',
    'temperature': '采样温度 0-2',
    'max_tokens': '最大生成 token 数',
    'top_k': 'Top K 结果数',
    'top_n': 'Top N 结果数',
    'limit': '限制数量',
    'session_id': '会话 ID',
    'to_session': '目标 session ID',
    'agent_id': 'Agent ID',
    'action': '操作类型',
    'data': '数据',
    'payload': '业务负载',
    'params': '参数',
    'metadata': '元数据',
    'tags': '标签列表',
    'input': '输入',
    'output': '输出',
    'text': '文本',
    'prompt': 'Prompt 文本',
    'response': '响应文本',
    'tool_name': '工具名称',
    'arguments': '工具参数',
    'endpoint_id': '端点 ID',
    'tier': '层级 (free/lite/standard/premium/flagship)',
    'channel': '通道名 (ch1/ch2/ch3)',
    'method': 'HTTP 方法 / 算法',
    'context': '上下文',
    'criteria': '标准列表',
    'config': '配置',
    'tasks': '任务列表',
    'steps': '步骤列表',
    'workflow': '工作流',
    'depends_on': '依赖步骤',
    'optional': '是否可选',
    'path': '文件路径',
    'fail_on': '失败阈值',
    'no_block': '是否不阻塞',
    'score': '分数',
    'level': '等级 / 严重度',
    'min_support': '最小支持数',
    'min_confidence': '最小置信度',
    'priority': '优先级',
    'queries': '查询列表',
    'windows': '窗口列表',
    'tokens': 'token 数量',
    'requested': '请求的资源量',
    'capacity': '容量',
    'refill_rate': '补充速率',
    'lock_id': '锁 ID',
    'lock': '锁对象',
    'session': '会话对象',
    'merge': '合并配置',
    'rules': '规则列表',
    'modes': '模式列表',
    'block': '是否阻塞',
    'topic': '主题',
    'judge_model': '评审模型',
    'reference': '参考答案',
    'evidences': '证据列表',
    'evidence': '证据',
    'claim': '声明',
    'baseline': '基线',
    'gaps': '差距',
    'residual_risk': '剩余风险',
    'reference_answer': '参考答案 (可选)',
    'goal': '目标',
    'goals': '目标列表',
    'criterion': '评估标准',
    'generated_ceiling': '是否生成上限',
    'category': '类别',
    'cat': '类别',
    'phase': '阶段',
    'check_id': '检查 ID',
    'checkpoints': '检查点列表',
    'word': '单词',
    'corpus': '语料库',
    'max_results': '最大结果数',
    'args': '参数',
    'kwargs': '关键字参数',
    'judgment_model': '评审模型',
    'judge_response': '评审响应',
    'judge_response_swapped': '交换后的评审响应',
    'response_a': '响应 A',
    'response_b': '响应 B',
    'lock_state': '锁状态',
    'duration_ms': '持续时间 (ms)',
    'flag': '标志',
    'is_blocked': '是否被阻塞',
    'user_id': '用户 ID',
    'event': '事件',
    'event_type': '事件类型',
    'event_data': '事件数据',
    'session_state': '会话状态',
    'caller': '调用者',
    'task_id': '任务 ID',
    'trace_id': '追踪 ID',
    'span_id': 'Span ID',
    'parent_id': '父 ID',
    'attempts': '尝试次数',
    'max_attempts': '最大尝试次数',
    'delay': '延迟',
    'min_level': '最小级别',
    'started_at': '开始时间',
    'ended_at': '结束时间',
    'completed': '是否完成',
    'skip': '是否跳过',
    'force': '是否强制',
    'query_string': '查询字符串',
    'filter': '过滤器',
    'sort': '排序',
    'sort_by': '排序字段',
    'min_cost': '最小成本',
    'max_cost': '最大成本',
    'encoding': '编码',
    'output_format': '输出格式',
    'command': '命令',
    'pattern': '模式',
    'match_type': '匹配类型',
    'reason': '原因',
    'spec': '规格',
    'rule': '规则',
    'id': 'ID',
    'state': '状态',
    'sub_action': '子操作',
    'outcome': '结果',
    'resource': '资源',
    'actor': '操作者',
    'since': '起始时间',
    'include': '包含',
    'exclude': '排除',
    'flag_blocked': '是否标记阻塞',
    'flag_disabled': '是否标记禁用',
    'enable': '是否启用',
    'disable': '是否禁用',
    'content_filter': '内容过滤器',
    'max_turns': '最大轮次',
    'turn_id': '轮次 ID',
    'data_id': '数据 ID',
    'provider': 'Provider 名称',
    'protocol': '协议',
    'host': '主机',
    'port': '端口',
    'username': '用户名',
    'password': '密码',
    'token': 'Token',
    'old_password': '旧密码',
    'new_password': '新密码',
    'field': '字段',
    'fields': '字段列表',
    'mode': '模式',
    'latency': '延迟',
    'cost': '成本',
    'rounds': '轮次',
    'round_threshold': '轮次阈值',
    'warn_threshold': '警告阈值',
    'block_threshold': '阻塞阈值',
    'feature': '特性',
    'features': '特性列表',
    'format': '格式',
    'responses': '响应列表',
    'providers': 'Provider 列表',
    'fail_at': '失败位置',
    'max_retries': '最大重试',
    'strategy': '策略',
    'llm': '大模型配置',
    'fallback_chain': '回退链',
    'fallback_strategies': '回退策略列表',
    'routing_strategy': '路由策略',
    'routing_config': '路由配置',
    'chunk_size': '块大小',
    'overlap': '重叠',
    'max_cost_ratio': '最大成本比',
    'tools': '工具列表',
    'tool_calls': '工具调用列表',
    'function_call': '函数调用',
    'tool_choice': '工具选择',
    'response_format': '响应格式',
    'stream': '是否流式',
    'main_model': '主模型',
    'ref_model': '参考模型',
    'ref_strategy': '参考策略',
    'max_latency_ms': '最大延迟 (ms)',
    'cost_ratio_cap': '成本比上限',
    'main_strategy': '主策略',
    'ref_enabled': '是否启用参考',
    'truthful': '真实性',
    'logical': '逻辑性',
    'helpful': '有用性',
    'harmless': '无害性',
    'insightful': '洞察性',
    'comprehensive': '全面性',
    'concise': '简洁性',
    'relevance': '相关性',
    'coherence': '连贯性',
    'creativity': '创造性',
    'depth': '深度',
    'breadth': '广度',
    'specificity': '具体性',
    'correctness': '正确性',
    'efficiency': '效率',
    'robustness': '鲁棒性',
    'readability': '可读性',
    'maintainability': '可维护性',
    'safety': '安全性',
    'completeness': '完整性',
    'consistency': '一致性',
    'all_text': '所有文本',
    'all_scores': '所有分数',
    'test_count': '测试数量',
    'pass_count': '通过数量',
    'fail_count': '失败数量',
    'score_threshold': '分数阈值',
    'min_score': '最低分数',
    'input_tokens': '输入 token',
    'output_tokens': '输出 token',
    'max_total_tokens': '最大总 token',
    'addrs': '地址列表',
    'metric': '指标',
    'metrics': '指标列表',
    'snapshot': '快照',
    'cleanup': '清理',
    'reset': '重置',
    'enabled': '是否启用',
    'set': '集合',
    'reduce': '归约',
    'key': '键',
    'value': '值',
    'layer': '层级',
    'explicit': '是否显式',
    'mode_permission': '权限模式',
    'label': '标签',
    'remove': '删除',
    'stop_reason': '停止原因',
    'model': '模型',
    'delta': '增量',
    'tool_id': '工具 ID',
    'name_tool': '工具名',
    'input_tool': '工具输入',
    'tool_use_id': '工具使用 ID',
    'is_error': '是否错误',
    'error_type': '错误类型',
    'message_err': '错误消息',
    'chat_response': '聊天响应',
    'anthropic_request': 'Anthropic 请求',
    'max_tokens_out': '最大输出 token',
    'parse_strategy': '解析策略',
    'min_relevance': '最小相关性',
    'key_filter': '键过滤',
    'path_filter': '路径过滤',
    'key_ids': '键 ID 列表',
    'function': '函数',
    'proposal_id': '提案 ID',
    'version': '版本',
    'content_type': '内容类型',
    'code_id': '代码 ID',
    'decode_id': '解码 ID',
    'traceparent': 'Trace 上下文',
    'span_name': 'Span 名称',
    'text_decoded': '解码文本',
    'panels': '面板列表',
    'rating': '评分',
    'parsed': '已解析',
    'judge_score': '评审分数',
    'parsed_battle': '已解析对战',
    'swap_battle': '交换对战',
    'language': '语言',
    'file_path': '文件路径',
    'command_str': '命令字符串',
    'mx_text': 'MX 文本',
    'fanin_text': 'Fanin 文本',
    'cli_command': 'CLI 命令',
    'parsed_mx': '已解析 MX',
    'fanin': 'Fanin',
    'threshold': '阈值',
    'max_size': '最大大小',
    'metadata_in': '输入元数据',
    'a': '字符串 A',
    'b': '字符串 B',
    'level_str': '级别字符串',
    'str_a': '字符串 A',
    'str_b': '字符串 B',
    'main_arg': '主参数',
    'max_results_search': '最大搜索结果',
    'panes': '面板列表',
    'pane_id': '面板 ID',
    'cwd': '工作目录',
    'env_vars': '环境变量',
    'artifacts': '工件列表',
    'artifact_id': '工件 ID',
    'type_artifact': '工件类型',
    'frozen_path': '冻结路径',
    'freeze_zone': '冻结区域',
    'sentinel_id': '哨兵 ID',
    'sentinel': '哨兵',
    'added_at': '添加时间',
    'added_by': '添加者',
    'reason_freeze': '冻结原因',
    'check_name': '检查名',
    'check_at': '检查时间',
    'event_id': '事件 ID',
    'event_payload': '事件负载',
    'event_ts': '事件时间戳',
    'ag_id': 'Agent ID',
    'recent_n': '最近 N 条',
    'pane_cmd': '面板命令',
    'envs': '环境变量',
    'check_pass': '检查通过',
    'check_status': '检查状态',
    'check_warnings': '检查警告',
    'id_check': '检查 ID',
    'channel_type': '通道类型',
    'chain_info_arg': 'Chain info 参数',
    'sub_action_chain': 'Chain 子操作',
    'main_model_ref': '主模型引用',
    'ref_model_ref': '参考模型引用',
    'ref_strategy_arg': '参考策略参数',
    'fault_at': '故障位置',
    'providers_list': 'Provider 列表',
    'providers_spec': 'Provider 规格',
    'doc_str': '文档字符串',
    'check_root_id': '检查根 ID',
    'criteria_list': '标准列表',
    'ears_text': 'EARS 文本',
    'ears_parsed': 'EARS 解析',
    'tree_artifact': '工件树',
    'tree_response': '响应树',
    'tree_id': '树 ID',
    'add_root_id': '添加根 ID',
    'add_criteria': '添加标准',
    'add_text': '添加文本',
    'parse_ears': '解析 EARS',
    'cmd_str': '命令字符串',
    'created_by': '创建者',
    'proposal_text': '提案文本',
    'get_id': '获取 ID',
    'latest_id': '最新 ID',
    'parse_rating': '解析评分',
    'parse_battle_id': '解析对战 ID',
    'swap_battle_id': '交换对战 ID',
    'swap_resp_a': '交换响应 A',
    'swap_resp_b': '交换响应 B',
    'rate_resp': '评分响应',
    'set_key': '设置键',
    'set_value': '设置值',
    'set_layer': '设置层',
    'set_explicit': '设置显式',
    'unset_key': '取消键',
    'unset_layer': '取消层',
    'merge_layers': '合并层',
    'permission_mode': '权限模式',
    'checkpoint_name': '检查点名',
    'checkpoint_payload': '检查点负载',
    'mx_text_arg': 'MX 文本参数',
    'mx_fpath': 'MX 文件路径',
    'mx_lang': 'MX 语言',
    'mx_command': 'MX 命令',
    'canary_prompt': 'Canary prompt',
    'canary_strategy': 'Canary 策略',
    'canary_response': 'Canary 响应',
    'canary_token': 'Canary 令牌',
    'wrap_content': '包装内容',
    'wrap_source': '包装源',
    'wrap_trust': '包装信任',
    'wrap_max_length': '包装最大长度',
    'unwrap_text': '解包文本',
    'sanitize_content': '清理内容',
    'fuzzy_text': '模糊文本',
    'fuzzy_metadata': '模糊元数据',
    'fuzzy_threshold': '模糊阈值',
    'fp_text': '指纹文本',
    'fp_a': '指纹 A',
    'fp_b': '指纹 B',
    'fp_level': '指纹级别',
    'fp_metadata': '指纹元数据',
    'fp_max_size': '指纹最大大小',
    'ts_tool_name': 'TS 工具名',
    'ts_arguments': 'TS 参数',
    'ac_action': 'AC 操作',
    'ac_request': 'AC 请求',
    'ac_delta': 'AC 增量',
    'ac_model': 'AC 模型',
    'ac_stop_reason': 'AC 停止原因',
    'ac_tool_id': 'AC 工具 ID',
    'ac_name': 'AC 名称',
    'ac_input': 'AC 输入',
    'ac_tool_use_id': 'AC 工具使用 ID',
    'ac_content': 'AC 内容',
    'ac_is_error': 'AC 是否错误',
    'ac_error_type': 'AC 错误类型',
    'ac_message': 'AC 消息',
    'ac_chat_response': 'AC 聊天响应',
    'ac_anthropic_request': 'AC Anthropic 请求',
    'tb_key': '令牌桶键',
    'tb_tokens': '令牌桶 tokens',
    'tb_capacity': '令牌桶容量',
    'tb_refill_rate': '令牌桶补充速率',
    'rd_method': 'RD 方法',
    'rd_path': 'RD 路径',
    'rd_body': 'RD body',
    'rd_source': 'RD 源',
    'rd_response': 'RD 响应',
    'tr_action': 'Trace 操作',
    'tr_trace_id': 'Trace ID',
    'tr_span_id': 'Trace Span ID',
    'tr_name': 'Trace 名称',
    'tr_duration_ms': 'Trace 持续时间',
    'tr_status': 'Trace 状态',
    'tr_limit': 'Trace 限制',
    'tr_traceparent': 'Trace parent',
    'ag_service': 'Agent service',
    'ag_method': 'Agent method',
    'ag_payload': 'Agent payload',
    'ag_calls': 'Agent calls 列表',
    'ag_name': 'Agent name',
    'ag_steps': 'Agent steps',
    'ag_description': 'Agent 描述',
    'ag_input': 'Agent input',
    'wf_name': 'Workflow 名称',
    'wf_steps': 'Workflow 步骤',
    'wf_input': 'Workflow 输入',
    'get_field': '字段',
}

# Pattern: `    field: Optional[Any] = None` → `    field: Optional[Any] = Field(None, description="...")`
pattern = re.compile(r'^(\s+)([a-z_]\w*):\s+Optional\[Any\]\s*=\s*None\s*$', re.MULTILINE)
def replace(m):
    indent, name = m.group(1), m.group(2)
    desc = DESC.get(name, f'{name} 字段')
    return f'{indent}{name}: Optional[Any] = Field(None, description="{desc}")'

new_src = pattern.sub(replace, src)

# Count changes
old_count = src.count(' = None\n')
new_count = new_src.count(' = None\n')
field_count = new_src.count('Field(None, description=')
print(f"converted {field_count} fields to Field with description")

p.write_text(new_src, encoding="utf-8")
