apiVersion: v1
kind: Service
metadata:
  name: {{ include "moa-gateway-pro.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "moa-gateway-pro.name" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "moa-gateway-pro.name" . }}
